export enum UserRole {
  ADMIN = 'ADMIN',
  PRODUCTION_MANAGER = 'PRODUCTION_MANAGER',
  SALES_REP = 'SALES_REP',
  FINANCE = 'FINANCE',
  WAREHOUSE_STAFF = 'WAREHOUSE_STAFF',
  PRODUCT_MANAGER = 'PRODUCT_MANAGER',
  RETAIL_STAFF = 'RETAIL_STAFF',
}


